### ISSUE TITLE
confusing wording?

### ISSUE THREAD

**Issue by d-d-d-dalia** [learn-co-curriculum/rails-dynamic-request-readme#17]
The below portion of the readme seems a little confusing -- the route is supposed to be added to routes.rb, but this wording almost makes it seem like it goes in the posts controller. I see how it is meant to be read, but as a newbie, it threw me off.

Running rspec gives us an expected error of: ActionController::RoutingError: No route matches [GET] "/posts/1". To correct this error, let's draw a route that maps to a show action in the PostsController:

get 'posts/:id', to: 'posts#show'

A quick fix would be to add "in config/routes.rb" to the second sentence: "To correct this error, let's draw a route *in config/routes.rb* that maps to a show action in the PostsController:".

**Comment by curiositypaths** [comment]
Hi there,

Thank you for taking the time to contribute to our curriculum. We will update the routes read me to reflect your suggestions.

Thanks! 💙
