### ISSUE TITLE
Test will not find show route 

### ISSUE THREAD

**Issue by justinddaniel** [learn-co-curriculum/rails-dynamic-request-readme#19]
Student copied exact solution, it was clearly working in browser, but test could not return a success for finding the show route.

**Comment by jd2rogers2** [comment]
saw the same thing yesterday but after looking again i think the student must have used a generator to build the post_controller and it had generated an extra test too
for any future TCs: double check that they only have the 3 original tests in spec/features/post_spec.rb

**Comment by jenmyers** [comment]
Since this doesn't seem like an issue in the curriculum, closing for now.
