### ISSUE TITLE
'View on GitHub' -> 404

### ISSUE THREAD

**Issue by onyoo** [learn-co-curriculum/rails-dynamic-request-readme#2]
<img width="387" alt="screen shot 2016-01-06 at 3 28 18 pm" src="https://cloud.githubusercontent.com/assets/14326883/12144749/277c9ea6-b48a-11e5-9d76-b7bb28c18ecc.png">

**Comment by onyoo** [comment]
https://github.com/learn-co-students/rails-dynamic-request-readme-v-000

**Comment by AnnJohn** [comment]
should be fixed now. thanks!
