### ISSUE TITLE
Comment in erb tag ReadMe, extra space

### ISSUE THREAD

**Issue by kai021998** [learn-co-curriculum/rails-dynamic-request-readme#21]
line 128, should not have space between erb tag and the hashtag

**Comment by maxwellbenton** [comment]
Thank you for spotting this issue and providing feedback.

We have updated the materials and believe your issue to have been resolved.

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this issue. 💙
