### ISSUE TITLE
Bug on the site

### ISSUE THREAD

**Issue by Asilver-jpg** [learn-co-curriculum/rails-dynamic-request-readme#29]
Sometimes when I duplicate a tab, or at certain times, the curriculum will have 2 tabs of the same link.

**Comment by lizbur10** [comment]
Hi there,

I'm having difficulty reproducing the issue, so I'm going to close it for now.

If you can provide further detail about the steps required to reproduce the issue and any additional relevant information about your development environment (local or IDE), I'd be happy to take a second look!

As always, thanks for contributing! 💙
